\LoadClass[11pt]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
%\usepackage[ngerman]{babel}

\usepackage[draft]{graphicx}
\usepackage{longtable}
\usepackage{float}
\usepackage{wrapfig}
\usepackage{soul}
\usepackage{textcomp}
\usepackage{marvosym}

\usepackage{wasysym}
\usepackage{latexsym}
\usepackage{amsfonts, amsmath, amssymb}

\usepackage{hyperref}

\usepackage{color, colortbl}
\usepackage[table]{xcolor}

\usepackage{multicol} 

\numberwithin{equation}{section}
\numberwithin{table}{section}
\numberwithin{figure}{section}

\usepackage{caption}
\usepackage{fancyhdr}
\usepackage{listings}
\lstset{language=python}

\usepackage{url}
\usepackage{cleveref}

\newcommand{\topspace}{\vrule height 15pt width 0pt}

\newcommand{\notetitle}[4]{
    \begin{center}
      {\Large \bf #1}  \\[9pt]
      {\Large \bf #2}  \\[12pt]
      {\large #3}  \\[6pt]
      {\normalsize #4}  \\[36pt]
    \end{center}}

